### ISSUE TITLE
canvas先放大再缩小，canvas上的节点消失不见

### ISSUE THREAD

**Issue by sunkingsss** [auto-workflow/aiflow#18]

**Comment by zhoushengmufc** [comment]
使用内置的方法：setScale(scale, center)

**Comment by sunkingsss** [comment]
zoomin() {
				this.zoom += 0.1;
				this.zoom = Math.min(2, this.zoom);
				this.aiFlow.setScale(this.zoom, [0, 0]);
			},
			zoomout() {
				this.zoom -= 0.1;
				this.zoom = Math.min(0.1, this.zoom);
				this.aiFlow.setScale(this.zoom, [0, 0]);
			},
			resetZoom() {
				this.zoom = 1;
				this.aiFlow.setScale(this.zoom, [0, 0]);
			},
我就是使用的setscale方法调用的

**Comment by sunkingsss** [comment]
不好意思，是我犯蠢了，感谢
