### ISSUE TITLE
调整输入圈

### ISSUE THREAD

**Issue by ShawSun-thu** [auto-workflow/aiflow#20]
有办法为已有节点增加输入圈吗？或是让一个输入圈能接受多个输入，而不是只能接受一个输入？

**Comment by zhoushengmufc** [comment]
globalConfig.relationMapping 关系映射方式 目前支持一对多(o2m)、多对多(m2m)、暂不支持多对一(m2o)、一对一(o2o),默认值o2m

**Comment by zhoushengmufc** [comment]
此配置参数调整为m2m即可

**Comment by ShawSun-thu** [comment]
谢谢，问题解决了
